/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myquizapp.gui;

import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import myquizapp.dao.PerformanceDAO;
import myquizapp.dao.QuestionDAO;
import myquizapp.pojo.Answer;
import myquizapp.pojo.AnswerStore;
import myquizapp.pojo.Exam;
import myquizapp.pojo.Performance;
import myquizapp.pojo.Question;
import myquizapp.pojo.QuestionStore;
import myquizapp.pojo.UserProfile;

/**
 *
 * @author Windows
 */
public class TakeTestFrame extends javax.swing.JFrame {

    private Exam exam;
    private QuestionStore qstore;
    private AnswerStore astore;
    private int pos,qno;
    public TakeTestFrame() {
        initComponents();
        qstore=new QuestionStore();
        astore=new AnswerStore();
        qno=1;
        txtUsername.setText(UserProfile.getUsername());
        lblQno.setText(lblQno.getText()+qno);
    }


    public TakeTestFrame(Exam exam){
    this();
    this.exam=exam;
    lblTitle.setText(exam.getLANGUAGE().toUpperCase()+" PAPER");
    loadQuestions();
    showQuestions();
    
    }
    public void loadQuestions(){
    try{
    ArrayList<Question> questionList=QuestionDAO.getQuestionsByExamId(exam.getEXAMID());
    for(Question obj:questionList){
    qstore.addQuestion(obj);
    }
    }catch(SQLException e){
    JOptionPane.showMessageDialog(null,"Error contacting database/loading questions","Erroe!",JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
    }
    }
    public void showQuestions(){
   
    Question question=qstore.getQuestion(pos);
    buttonGroup1.clearSelection();//to clear buttons
    txtQuestion.setText(question.getQuestion());
    jrOption1.setText(question.getAnswer1());
    jrOption2.setText(question.getAnswer2());
    jrOption3.setText(question.getAnswer3());
    jrOption4.setText(question.getAnswer4());
    Answer answer=astore.getAnswerByQno(qno);
   if(answer==null)
       return;
   String chosenAnswer=answer.getChosenAnswer();
   switch(chosenAnswer){
       case "Answer1":
           jrOption1.setSelected(true);
       case "Answer2":
            jrOption2.setSelected(true);
       case "Answer3":
           jrOption3.setSelected(true);
       case "Answer4":
           jrOption4.setSelected(true);
   }
   }
    
    public String getUserAnswer(){
    if(jrOption1.isSelected())
        return "Answer1";
    else if(jrOption2.isSelected())
        return "Answer2";
    else if(jrOption3.isSelected())
        return "Answer3";
    else if(jrOption4.isSelected())
        return "Answer4";
    else 
        return null;
    
    }
    /**
     
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLogout = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        lblQno = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        jrOption1 = new javax.swing.JRadioButton();
        jrOption2 = new javax.swing.JRadioButton();
        jrOption3 = new javax.swing.JRadioButton();
        jrOption4 = new javax.swing.JRadioButton();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLogout.setBackground(new java.awt.Color(0, 0, 0));
        jLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 0, 0));
        jLogout.setText("LogOut");
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLogoutMouseExited(evt);
            }
        });

        txtUsername.setBackground(new java.awt.Color(0, 0, 0));
        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 0, 0));
        txtUsername.setText("Welcome");

        lblQno.setBackground(new java.awt.Color(0, 0, 0));
        lblQno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQno.setForeground(new java.awt.Color(255, 0, 0));
        lblQno.setText("Question no:");

        txtQuestion.setEditable(false);
        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane2.setViewportView(txtQuestion);

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 102, 0));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 102, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDone.setBackground(new java.awt.Color(0, 0, 0));
        btnDone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDone.setForeground(new java.awt.Color(255, 102, 0));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        btnPrevious.setBackground(new java.awt.Color(0, 0, 0));
        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 102, 51));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        jrOption1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption1);
        jrOption1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption1.setForeground(new java.awt.Color(255, 51, 0));
        jrOption1.setText("jRadioButton1");

        jrOption2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption2);
        jrOption2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption2.setForeground(new java.awt.Color(255, 51, 0));
        jrOption2.setText("jRadioButton2");

        jrOption3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption3);
        jrOption3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption3.setForeground(new java.awt.Color(255, 51, 0));
        jrOption3.setText("jRadioButton3");

        jrOption4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption4);
        jrOption4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption4.setForeground(new java.awt.Color(255, 51, 0));
        jrOption4.setText("jRadioButton4");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("TEST GOING ON");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myquizapp/gui/good luck2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblQno)))
                .addGap(100, 100, 100)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jrOption3)
                                .addGap(133, 133, 133)
                                .addComponent(jrOption4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jrOption1)
                                .addGap(123, 123, 123)
                                .addComponent(jrOption2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnNext)
                        .addGap(44, 44, 44)
                        .addComponent(btnPrevious)
                        .addGap(39, 39, 39)
                        .addComponent(btnCancel)
                        .addGap(53, 53, 53)
                        .addComponent(btnDone)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle)
                        .addComponent(txtUsername))
                    .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblQno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(324, 324, 324))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrOption1)
                            .addComponent(jrOption2))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrOption3)
                            .addComponent(jrOption4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPrevious)
                                .addComponent(btnCancel)
                                .addComponent(btnDone)))
                        .addGap(109, 109, 109))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        UserLoginScreen userlogin = new UserLoginScreen();
        userlogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseEntered
        jLogout.setFont(new Font("Tahoma", Font.ITALIC, 12));             // TODO add your handling code here:
    }//GEN-LAST:event_jLogoutMouseEntered

    private void jLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseExited
        jLogout.setFont(new Font("Tahoma", Font.BOLD, 12));             // TODO add your handling code here:
    }//GEN-LAST:event_jLogoutMouseExited

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        String chosenAnswer=getUserAnswer();
        if(chosenAnswer!=null){
        Question question=qstore.getQuestion(pos);
        System.out.println("Positin is "+pos+"Question is "+question);
        String correctAnswer=question.getCorrectAnswer();
        System.out.println(correctAnswer);//null
        Answer newanswer=new Answer(exam.getEXAMID(),exam.getLANGUAGE(),qno,chosenAnswer,correctAnswer);
        System.out.println(newanswer);//obj
        System.out.println("stored in ans object");
        Answer answer=astore.getAnswerByQno(qno);
        System.out.println(answer);//null
        if(answer==null)
            astore.addAnswer(newanswer);
        else{
        if(newanswer.getChosenAnswer().equals(answer.getChosenAnswer())==false){
        int apos=astore.removeAnswer(answer);
        astore.setAnswerAt(apos, newanswer);
        }
        }
        }
        System.out.println(pos);
        pos++;
      
        //pos++;
        if(pos>=qstore.getCount()){
        JOptionPane.showMessageDialog(null,"Test Has been completed","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
            btnNext.setEnabled(false);
            btnPrevious.setEnabled(false);
            System.out.println("Inside terminating control"+pos);
            pos=0;
          return;
        }
        qno++;
        
        if(qno>qstore.getCount())
            qno=1;
        lblQno.setText("Question No"+qno);
        showQuestions();
        System.out.println(qno);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ChoosePaperFrame pf = new ChoosePaperFrame();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
       
        String chosenAnswer=getUserAnswer();
        if(chosenAnswer!=null){
        Question question=qstore.getQuestion(pos);
        String correctAnswer=question.getCorrectAnswer();
        Answer newanswer=new Answer(exam.getEXAMID(),exam.getLANGUAGE(),qno,chosenAnswer,correctAnswer);
        System.out.println("sad");
        Answer answer=astore.getAnswerByQno(qno);
        if(answer==null)
            astore.addAnswer(newanswer);
        else{
        if(newanswer.getChosenAnswer().equals(answer.getChosenAnswer())==false){
        int apos=astore.removeAnswer(answer);
        astore.setAnswerAt(apos, newanswer);
        }
        }
        }
        int right=0,wrong=0;
        for(Question question:qstore.getAllQuestions()){
        int qno=question.getQno();
        Answer answer=astore.getAnswerByQno(qno);
        if(answer==null)
            continue;
        else
        {
        String chosenAnswer1=answer.getChosenAnswer();
        String correctAnswer=answer.getCorrectAnswer();
        if(chosenAnswer1.equals(correctAnswer))
            ++right;
        else
            ++wrong;
        }
        
        }
        String reportCard="Total Questions: "+qstore.getCount();
        reportCard+="\nRight Answers: "+right;
        reportCard+="\nWrong Answers: "+wrong;
        reportCard+="\n UnAttempted :"+(qstore.getCount()-(right+wrong));
        JOptionPane.showMessageDialog(null,reportCard,"Your Result",JOptionPane.INFORMATION_MESSAGE);
        try{
        Performance performance =new Performance(UserProfile.getUsername(),exam.getEXAMID(),right,wrong,(qstore.getCount()-(right+wrong)),(double)right/qstore.getCount()*100,exam.getLANGUAGE());
        PerformanceDAO.addPerformance(performance);
        JOptionPane.showMessageDialog(null,"Your Performance has been successfully added to database","Exam",JOptionPane.INFORMATION_MESSAGE);
        ChoosePaperFrame paperFrame=new ChoosePaperFrame();
        paperFrame.setVisible(true);
        this.dispose();
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Error Connecting database");
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed

        String chosenAnswer=getUserAnswer();
        System.out.println(chosenAnswer);
        if(chosenAnswer!=null){
        Question question=qstore.getQuestion(pos);
        String correctAnswer=question.getCorrectAnswer();
        Answer newanswer=new Answer(exam.getEXAMID(),exam.getLANGUAGE(),qno,chosenAnswer,correctAnswer);
        System.out.println(newanswer);
        Answer answer=astore.getAnswerByQno(qno);
        if(answer==null)
            astore.addAnswer(answer);
        else{
            if(newanswer.getChosenAnswer().equals(answer.getChosenAnswer())==false)
            {
            int apos=astore.removeAnswer(answer);
            astore.setAnswerAt(apos,newanswer);
            }
        }
        }
        pos--;
        if(pos<0)
            pos=qstore.getCount()-1;
        qno--;
        if(qno<=0)
            qno=qstore.getCount();
        lblQno.setText("Question No "+qno);
        showQuestions();
    }//GEN-LAST:event_btnPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLogout;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jrOption1;
    private javax.swing.JRadioButton jrOption2;
    private javax.swing.JRadioButton jrOption3;
    private javax.swing.JRadioButton jrOption4;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtQuestion;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
